# Default values for cluster-registry-controller
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

localCluster:
  # specify to automatically provision the cluster object upon first start
  name: ""
  manageSecret: true

istio:
  revision: ""

podAnnotations: []
imagePullSecrets: []

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
securityContext:
  allowPrivilegeEscalation: false
image:
  repository: ghcr.io/cisco-open/cluster-registry-controller
  tag: v0.1.8
  pullPolicy: IfNotPresent

nodeSelector: {}
affinity: {}
tolerations: []
resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "300m"

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  annotations: {}

podDisruptionBudget:
  enabled: false

controller:
  leaderElection:
    enabled: true
    name: "cluster-registry-leader-election"
  log:
    format: json
    verbosity: 0
  workers: 2
  apiServerEndpointAddress: ""
  network:
    name: "default"
  coreResourceSource:
    enabled: true
