{{- if .Values.webhooks.clusterValidator.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "{{ include "cluster-registry-controller.fullname" . }}-{{ .Values.webhooks.clusterValidator.nameSuffix }}"
  namespace: {{ .Release.Namespace }}
webhooks:
- name: cluster-validator.clusterregistry.k8s.cisco.com
  clientConfig:
    service:
      name: "{{ include "cluster-registry-controller.fullname" . }}"
      namespace: {{ .Release.Namespace }}
      path: /validate-cluster
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  rules:
  - apiGroups:
      - clusterregistry.k8s.cisco.com
    apiVersions:
      - v1alpha1
    operations:
      - CREATE
      - UPDATE
    resources:
      - clusters
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
  admissionReviewVersions:
    - v1
{{- end -}}
