apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-registry-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-registry-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-registry-controller-aggregated
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      cluster-registry.k8s.cisco.com/controller-aggregated: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-registry-controller.fullname" . }}
  labels:
    {{- include "cluster-registry-controller.labels" . | nindent 4 }}
    cluster-registry.k8s.cisco.com/controller-aggregated: "true"
rules:
- apiGroups: ["clusterregistry.k8s.cisco.com"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups: [""]
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - update
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-registry-controller.fullname" . }}
  labels:
    {{- include "cluster-registry-controller.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: cluster-registry-controller-aggregated
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-registry-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-registry-reader
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-registry-reader-aggregated
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      cluster-registry.k8s.cisco.com/reader-aggregated: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "cluster-registry-reader"
  labels:
    {{- include "cluster-registry-controller.labels" . | nindent 4 }}
    cluster-registry.k8s.cisco.com/reader-aggregated: "true"
rules:
- apiGroups: ["clusterregistry.k8s.cisco.com"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-registry-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-registry-reader-aggregated
subjects:
- kind: ServiceAccount
  name: cluster-registry-reader
  namespace: {{ .Release.Namespace }}
