apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-registry-controller.fullname" . }}-reader
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-registry-controller.fullname" . }}-reader-aggregated
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      cluster-registry.k8s.cisco.com/reader-aggregated: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-registry-controller.fullname" . }}-reader
  labels:
    {{- include "cluster-registry-controller.labels" . | nindent 4 }}
    cluster-registry.k8s.cisco.com/reader-aggregated: "true"
rules:
- apiGroups: ["clusterregistry.k8s.cisco.com"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - namespaces
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-registry-controller.fullname" . }}-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-registry-controller.fullname" . }}-reader-aggregated
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-registry-controller.fullname" . }}-reader
  namespace: {{ .Release.Namespace }}
