name: Helm

on:
  push:
    tags:
      - "deploy/charts/v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.5.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          charts_dir: deploy/charts
